openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
x-kusk:
  mocking:
    enabled: true
  cors:
    origins: 
      - "*"
    methods:
     - GET 
     - POST
     - PUT
paths:
  /hello:
    get:
      summary: Get a list of things
      responses:
        200:
          description: A list of things
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
              example: 
                message: Hello World